### ISSUE TITLE
音视频同步

### ISSUE THREAD

**Issue by zhoujianhanyu** [wanliyang1990/wlplayer#1]
如果视频比音频慢了，好像没有做丢帧处理

**Comment by ywl5320** [comment]
恩 没有做丢帧处理 每一帧都播放出来了的，我觉得丢帧不是很好 所以就没有处理。你可以自己添加，判断时间超过了一定的大小 就跳过渲染就可以了，在video那个cpp文件里面

**Comment by ywl5320** [comment]
已增加了丢帧处理
