### ISSUE TITLE
发现某些是视频播放时时方向不对,竖的变成的横的

### ISSUE THREAD

**Issue by s949492225** [wanliyang1990/wlplayer#10]
1.发现某些是视频播放时时方向不对,竖的变成的横的
因为某些手机摄像头时装的方向不对,视频里时有方向信息的,建议对yuv进行旋转,
2.当view大小发生变化时,是否可以自动去适应?
3.是否能够加入视频包裹内容,拉伸,适配高度,适配宽度等功能?

**Comment by ywl5320** [comment]
你说的上面的功能都没问题的，你可以先自己看看源码，理解后就可以添加了，有不懂得随时可以问我，这样学习效果才是最好的。
