### ISSUE TITLE
播放视频全部变成黑白的了

### ISSUE THREAD

**Issue by billsinla** [wanliyang1990/wlplayer#12]

**Comment by billsinla** [comment]
![Uploading 93B5CAE407CAAA753A8FE3EB9C797D67.jpg…]()

**Comment by billsinla** [comment]
![93b5cae407caaa753a8fe3eb9c797d67](https://user-images.githubusercontent.com/15274049/47903449-afd62680-debe-11e8-95e8-b3eb4f433f80.jpg)

**Comment by ywl5320** [comment]
硬解码渲染我加了一个黑白滤镜的（主要是为了演示滤镜功能） 解决方法看这里哈https://github.com/wanliyang1990/wlplayer/issues/6
