### ISSUE TITLE
发现有些视频软解码出来后不是yuv420p,然后播放黑屏

### ISSUE THREAD

**Issue by s949492225** [wanliyang1990/wlplayer#13]
发现有些视频软解码出来后不是yuv420p,然后转换后黑屏,用了课程里的,和这里的都不行,然后我导出转换后的yuv发现是正常的,请问是纹理方面有问题吗

**Comment by ywl5320** [comment]
问题解决了没

**Comment by s949492225** [comment]
发现是我自己的问题,很想默默的消失这个issue,发现搞不掉,尴尬
