### ISSUE TITLE
视频只有声音没有图像黑屏

### ISSUE THREAD

**Issue by yu12mang** [wanliyang1990/wlplayer#4]
在魅族手机上测试只有声音 没有视频图像的问题 请问要怎么解决？

**Comment by ywl5320** [comment]
我暂时没有相关的机型，所以我这里测试不了。。。应该是硬解码兼容性问题，需要测试才知道。

**Comment by ywl5320** [comment]
把wlplayer.java里面这里改成这个试试：
while (index >= 0) {
                    mediaCodec.releaseOutputBuffer(index, true);
                    index = mediaCodec.dequeueOutputBuffer(info, 10);
                }

**Comment by yu12mang** [comment]
用你给的方法可以了 非常感谢大神
