### ISSUE TITLE
请问GPU解码是如何实现的？

### ISSUE THREAD

**Issue by zhanghuicuc** [wanliyang1990/wlplayer#5]
在readme中看到这一条：
3、优先选用GPU解码，解码速度更快。

请问这一点是如何实现的？谢谢。

**Comment by ywl5320** [comment]
就是把解码前的Avpacket包用MediaCodec来解码，具体可以看博客或看源码：https://blog.csdn.net/ywl5320/article/details/78965039

**Comment by zhanghuicuc** [comment]
哦，原来就是指MediaCodec硬解啊，感谢。个人感觉，严格来说这应该不算gpu解码，移动设备芯片上有专门的视频解码模块，但是和gpu并不是一个东西。

**Comment by ywl5320** [comment]
恩 在Android上要实现更高效的解码就是用MediaCodec来实现解码的，当然它不是完全都是硬解码部分，还是封装了自己的代码逻辑，只是底层会调用硬解来加速解码过程而已。
