### ISSUE TITLE
rtmp和rtsp

### ISSUE THREAD

**Issue by galileolvpo** [wanliyang1990/wlplayer#6]
为什么播放rtmp流的时候是黑白的，
放rtsp只有声音

**Comment by ywl5320** [comment]
1、黑白是因为我在res/raw/fragment_mediacodec.glsl文件中加了滤镜，你可以改成这样：
void main() {
    gl_FragColor=texture2D(sTexture, v_texPo);
//    lowp vec4 textureColor = texture2D(sTexture, v_texPo);
//    float gray = textureColor.r * 0.299 + textureColor.g * 0.587 + textureColor.b * 0.114;
//    gl_FragColor = vec4(gray, gray, gray, textureColor.w);
}
2、我这里播放rtsp（rtsp://184.72.239.149/vod/mp4://BigBuckBunny_175k.mov）有画面，你提供一下你的rtsp地址给我测试一下呢

**Comment by galileolvpo** [comment]
这个动画的rtsp我用vlc没打开，我记得我以前明明开过。。不知道是不是我这的问题，虽然地址最后少了个v，既然你说测下来没问题，我再好好看看。
然后我自己测得rtsp地址是我自己推到服务器的流，之前用ffmpeg做简单的拉流可以看到画面，现在想把音频加进去，做音视频同步，看到up的项目  正好学习一下，

**Comment by ywl5320** [comment]
恩 有问题就说出来 一起解决
