### ISSUE TITLE
使用wlPlayer.setOnlySoft(false); 解码后，视频是黑白色

### ISSUE THREAD

**Issue by NillRhoads** [wanliyang1990/wlplayer#7]
在代码里设置wlPlayer.setOnlySoft是false的时候，然后广播接收来的视频解码出来是黑白色。失去了彩色，想问下这是什么情况？wlPlayer.setOnlySoft设置成true的时候是有彩色的，但是解码很卡顿

**Comment by ywl5320** [comment]
这个是我为了展示一下滤镜功能所加的硬解码黑白滤镜，解决方法在这里：https://github.com/wanliyang1990/wlplayer/issues/6 。setOnlySoft设置是否只是软解码，当视频太高清了，软解码就会卡顿的。你可以看一下源码，才能更清楚里面做了什么，有问题也可以自己解决了。

**Comment by NillRhoads** [comment]
嗯嗯，解决了 感谢老师

**Comment by ywl5320** [comment]
客气了
