### ISSUE TITLE
wlplayer播放不了H265视频

### ISSUE THREAD

**Issue by kbxwn** [wanliyang1990/wlplayer#8]
请问作者wlplayer能播放H265视频吗，尝试打开H265的视频但是只有声音，没有画面

**Comment by ywl5320** [comment]
我这里测试可以播放H265的，你把你的测试视频通过网盘给我一测试下呢。

**Comment by kbxwn** [comment]
网盘地址：http://pan.baidu.com/s/1qXAexiO
网盘密码：hph3
早上又测试了一下，用公司的开发板，
wlplayer：播放h265视频时，有声音无画面
x-plore: 一个文件夹管理器自带的播放器，能够播放声音画面；
然后我把视频文件传到自己的手机上，
wlplayer：播放h265视频时，有声音有画面；
想问下这个播放是跟硬件有关的吗？

**Comment by ywl5320** [comment]
你这个是4K的视频，里面默认是硬解码，如果手机硬解码不支持4K播放的话，就不能显示画面，我的手机就是。你可以改成软解码来播放。

**Comment by kbxwn** [comment]
使用软解码：
wlPlayer.setOnlySoft(true);
通过打印log，发现设置软解码后WlPlayer类的mediacodecInit(),mediacodecDecode()方法就不回调了，软解码是不用mediaCodec进行解码了吗？

**Comment by ywl5320** [comment]
软解码是用的opengl渲染的ffmpeg解码出来的yuv数据，不会用mediacodec。软解码可以播放不嘛，你换720P或者1080P的硬解码应该可以，你的那个设备不支持4K高清的解码。

**Comment by kbxwn** [comment]
了解了，目前项目没要求播放4K高清视频，换1080P及以下的视频源可以播放，应该是设备的问题，十分感谢您的回答，谢谢了

**Comment by ywl5320** [comment]
没事的哈
